local lspconfig = require("lspconfig")
local nvlsp = require("nvchad.configs.lspconfig")

lspconfig.csharp_ls.setup({
  on_init = nvlsp.on_init,
  on_attach = nvlsp.on_attach,
  capabilities = nvlsp.capabilities,
  root_dir = lspconfig.util.root_pattern("*.sln", "*.csproj"),
  filetypes = { "cs", "csproj", "sln" },
  init_options = {
    AutoGeneratedFileCodeLensEnabled = true,
    AnalyzeGeneratedFiles = true,
    DiagnosticsEnabled = true,
    GeneratedFileDataEnabled = true,
    SemanticTokensEnabled = true,
  },
})
