[font]
size = 16.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.85

[terminal]

[terminal.shell]
args = ["-NoLogo"]
program = 'C:\Program Files\PowerShell\7\pwsh.exe'
